#ifndef A300_BOOTLOADER_CONFIG_H
#define A300_BOOTLOADER_CONFIG_H

#include "firmware_layout.h"

#define BOOTLOADER_FLASH_BASE       BOOT_FLASH_BASE
#define BOOTLOADER_FLASH_SIZE       BOOT_FLASH_SIZE
#define APP_FLASH_END               FW_FLASH_END
#define APP_FLASH_MAX_SIZE          (APP_FLASH_END - APP_FLASH_BASE)
#define BOOTLOADER_RELEASE_MAX      BOOT_FLASH_SIZE
#define BOOTLOADER_INTERNAL_PAGE_SIZE 2048UL
#define BOOTLOADER_COPY_CHUNK_SIZE 256UL
#define BOOTLOADER_PAGE_SIZE        BOOTLOADER_COPY_CHUNK_SIZE
#define BOOTLOADER_TRIAL_LIMIT      3U
#define BOOTLOADER_PRODUCT_ID       0x41333030UL /* A300 */
#define BOOTLOADER_HARDWARE_ID      0x343036UL  /* 406 */

#endif
