#ifndef EXT_FLASH_LAYOUT_H
#define EXT_FLASH_LAYOUT_H
#include <stdint.h>
#include "spi_flash.h"
#define EXT_FLASH_CONFIG_ADDR 0x000000UL
#define EXT_FLASH_CONFIG_SIZE (2UL * FLASH_SECTOR_SIZE)
#define EXT_FLASH_CONFIG_SLOT_A_ADDR EXT_FLASH_CONFIG_ADDR
#define EXT_FLASH_CONFIG_SLOT_B_ADDR (EXT_FLASH_CONFIG_ADDR + FLASH_SECTOR_SIZE)
#define EXT_FLASH_CANDIDATE_ADDR 0x010000UL
#define EXT_FLASH_CANDIDATE_SIZE (448UL * 1024UL)
#define EXT_FLASH_FACTORY_ADDR 0x080000UL
#define EXT_FLASH_FACTORY_SIZE (256UL * 1024UL)
#define EXT_FLASH_LKG_ADDR 0x0C0000UL
#define EXT_FLASH_LKG_SIZE (256UL * 1024UL)
#define EXT_FLASH_RESUME_ADDR 0x100000UL
#define EXT_FLASH_RESUME_SIZE (64UL * 1024UL)
#define EXT_FLASH_BLIND_ADDR 0x110000UL
#define EXT_FLASH_BLIND_SIZE (644UL * 1024UL)
#define EXT_FLASH_AGNSS_ADDR 0x1B1000UL
#define EXT_FLASH_AGNSS_SIZE (FLASH_TOTAL_SIZE - EXT_FLASH_AGNSS_ADDR)
#define EXT_FLASH_AGNSS_META_ADDR EXT_FLASH_AGNSS_ADDR
#define EXT_FLASH_AGNSS_META_SIZE 0x1000UL
#define EXT_FLASH_AGNSS_SLOT_SIZE ((EXT_FLASH_AGNSS_SIZE - EXT_FLASH_AGNSS_META_SIZE) / 2UL)
#define EXT_FLASH_AGNSS_SLOT_A_ADDR (EXT_FLASH_AGNSS_ADDR + EXT_FLASH_AGNSS_META_SIZE)
#define EXT_FLASH_AGNSS_SLOT_B_ADDR (EXT_FLASH_AGNSS_SLOT_A_ADDR + EXT_FLASH_AGNSS_SLOT_SIZE)
#if (EXT_FLASH_CONFIG_ADDR % FLASH_SECTOR_SIZE) != 0 || (EXT_FLASH_CONFIG_SIZE % FLASH_SECTOR_SIZE) != 0
#error "configuration region must be sector aligned"
#endif
#if (EXT_FLASH_CONFIG_SLOT_A_ADDR + FLASH_SECTOR_SIZE) > EXT_FLASH_CONFIG_SLOT_B_ADDR
#error "configuration slots overlap"
#endif
#if (EXT_FLASH_CONFIG_SLOT_B_ADDR + FLASH_SECTOR_SIZE) > EXT_FLASH_CANDIDATE_ADDR
#error "configuration overlaps candidate"
#endif
#if ((EXT_FLASH_CANDIDATE_ADDR % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_CANDIDATE_SIZE % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_FACTORY_ADDR % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_FACTORY_SIZE % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_LKG_ADDR % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_LKG_SIZE % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_RESUME_ADDR % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_RESUME_SIZE % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_BLIND_ADDR % FLASH_SECTOR_SIZE) != 0) || ((EXT_FLASH_BLIND_SIZE % FLASH_SECTOR_SIZE) != 0)
#error "external flash regions must be sector aligned"
#endif
#if (EXT_FLASH_CANDIDATE_ADDR + EXT_FLASH_CANDIDATE_SIZE) > EXT_FLASH_FACTORY_ADDR
#error "external flash regions overlap: candidate/factory"
#endif
#if (EXT_FLASH_FACTORY_ADDR + EXT_FLASH_FACTORY_SIZE) > EXT_FLASH_LKG_ADDR
#error "external flash regions overlap: factory/lkg"
#endif
#if (EXT_FLASH_LKG_ADDR + EXT_FLASH_LKG_SIZE) > EXT_FLASH_RESUME_ADDR
#error "external flash regions overlap: lkg/resume"
#endif
#if (EXT_FLASH_RESUME_ADDR + EXT_FLASH_RESUME_SIZE) > EXT_FLASH_BLIND_ADDR
#error "external flash regions overlap: resume/blind"
#endif
#if (EXT_FLASH_BLIND_ADDR + EXT_FLASH_BLIND_SIZE) > EXT_FLASH_AGNSS_ADDR
#error "external flash regions overlap: blind/agnss"
#endif
#if (EXT_FLASH_AGNSS_ADDR + EXT_FLASH_AGNSS_SIZE) > FLASH_TOTAL_SIZE
#error "external flash layout exceeds device"
#endif
#if (EXT_FLASH_AGNSS_SLOT_B_ADDR + EXT_FLASH_AGNSS_SLOT_SIZE) > FLASH_TOTAL_SIZE
#error "AGNSS slots exceed device"
#endif
#if (EXT_FLASH_AGNSS_META_ADDR % FLASH_SECTOR_SIZE) != 0 || (EXT_FLASH_AGNSS_META_SIZE % FLASH_SECTOR_SIZE) != 0
#error "AGNSS metadata must be sector aligned"
#endif
#if (EXT_FLASH_AGNSS_SLOT_SIZE % FLASH_SECTOR_SIZE) != 0 || (EXT_FLASH_AGNSS_SLOT_A_ADDR % FLASH_SECTOR_SIZE) != 0 || (EXT_FLASH_AGNSS_SLOT_B_ADDR % FLASH_SECTOR_SIZE) != 0
#error "AGNSS slots must be sector aligned"
#endif
#if (EXT_FLASH_AGNSS_META_ADDR + EXT_FLASH_AGNSS_META_SIZE) > EXT_FLASH_AGNSS_SLOT_A_ADDR
#error "AGNSS metadata overlaps slot A"
#endif
#if (EXT_FLASH_AGNSS_SLOT_A_ADDR + EXT_FLASH_AGNSS_SLOT_SIZE) > EXT_FLASH_AGNSS_SLOT_B_ADDR
#error "AGNSS slots overlap"
#endif
#if (EXT_FLASH_AGNSS_SLOT_B_ADDR + EXT_FLASH_AGNSS_SLOT_SIZE) != (EXT_FLASH_AGNSS_ADDR + EXT_FLASH_AGNSS_SIZE)
#error "AGNSS slot boundary does not consume region exactly"
#endif
typedef enum { EXT_FLASH_OWNER_NONE=0, EXT_FLASH_OWNER_OTA, EXT_FLASH_OWNER_AGNSS, EXT_FLASH_OWNER_BLIND_ZONE, EXT_FLASH_OWNER_CONFIG } ext_flash_owner_t;
#endif
