#ifndef EXT_FLASH_LAYOUT_H
#define EXT_FLASH_LAYOUT_H
#include <stdint.h>
#include "spi_flash.h"
#define EXT_FLASH_CANDIDATE_ADDR 0x010000UL
#define EXT_FLASH_CANDIDATE_SIZE (448UL * 1024UL)
#define EXT_FLASH_FACTORY_ADDR 0x080000UL
#define EXT_FLASH_FACTORY_SIZE (256UL * 1024UL)
#define EXT_FLASH_LKG_ADDR 0x0C0000UL
#define EXT_FLASH_LKG_SIZE (256UL * 1024UL)
#define EXT_FLASH_RESUME_ADDR 0x100000UL
#define EXT_FLASH_RESUME_SIZE (64UL * 1024UL)
#define EXT_FLASH_BLIND_ADDR 0x110000UL
#define EXT_FLASH_BLIND_SIZE (644UL * 1024UL)
#define EXT_FLASH_AGNSS_ADDR 0x1B1000UL
#define EXT_FLASH_AGNSS_SIZE (FLASH_TOTAL_SIZE - EXT_FLASH_AGNSS_ADDR)
#define EXT_FLASH_AGNSS_META_SIZE 0x1000UL
#define EXT_FLASH_AGNSS_SLOT_SIZE ((EXT_FLASH_AGNSS_SIZE - EXT_FLASH_AGNSS_META_SIZE) / 2UL)
#define EXT_FLASH_AGNSS_SLOT_A_ADDR (EXT_FLASH_AGNSS_ADDR + EXT_FLASH_AGNSS_META_SIZE)
#define EXT_FLASH_AGNSS_SLOT_B_ADDR (EXT_FLASH_AGNSS_SLOT_A_ADDR + EXT_FLASH_AGNSS_SLOT_SIZE)
#if (EXT_FLASH_CANDIDATE_ADDR + EXT_FLASH_CANDIDATE_SIZE) > EXT_FLASH_FACTORY_ADDR
#error "external flash regions overlap: candidate/factory"
#endif
#if (EXT_FLASH_FACTORY_ADDR + EXT_FLASH_FACTORY_SIZE) > EXT_FLASH_LKG_ADDR
#error "external flash regions overlap: factory/lkg"
#endif
#if (EXT_FLASH_LKG_ADDR + EXT_FLASH_LKG_SIZE) > EXT_FLASH_RESUME_ADDR
#error "external flash regions overlap: lkg/resume"
#endif
#if (EXT_FLASH_RESUME_ADDR + EXT_FLASH_RESUME_SIZE) > EXT_FLASH_BLIND_ADDR
#error "external flash regions overlap: resume/blind"
#endif
#if (EXT_FLASH_BLIND_ADDR + EXT_FLASH_BLIND_SIZE) > EXT_FLASH_AGNSS_ADDR
#error "external flash regions overlap: blind/agnss"
#endif
#if (EXT_FLASH_AGNSS_ADDR + EXT_FLASH_AGNSS_SIZE) > FLASH_TOTAL_SIZE
#error "external flash layout exceeds device"
#endif
#if (EXT_FLASH_AGNSS_SLOT_B_ADDR + EXT_FLASH_AGNSS_SLOT_SIZE) > FLASH_TOTAL_SIZE
#error "AGNSS slots exceed device"
#endif
typedef enum { EXT_FLASH_OWNER_NONE=0, EXT_FLASH_OWNER_OTA, EXT_FLASH_OWNER_AGNSS, EXT_FLASH_OWNER_BLIND_ZONE, EXT_FLASH_OWNER_CONFIG } ext_flash_owner_t;
#endif
